name: Run Windows build
on:
  workflow_dispatch: {}
jobs:
  build:
    name: Run the Windows build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Check out my unity project.
        uses: actions/checkout@v4
        with:
          lfs: true
          
      # ファイル名にgitのハッシュを含めたいので$GITHUB_OUTPUTに保存しておく
      # - name: Set outputs
      #   id: vars
      #   run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      # クリーンアップで untracked なファイルを削除
      - name: Clean up untracked files
        run: |
          git clean -fdx


      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Unityプロジェクトのビルド
      # 設定しない場合、buildフォルダに出力される
      - name: Windows build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 2022.3.39f1  #ここに使うUnityのバージョンを入れる
          allowDirtyBuild: true

      # 成果物をZIPにしてアップロードする
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ steps.vars.outputs.sha_short }}
          path: build
